# Generated by Django 6.0.1 on 2026-01-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('task_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('task_due_date', models.DateField()),
                ('view_order', models.PositiveIntegerField(db_index=True, unique=True)),
            ],
        ),
    ]
