# Generated by Django 6.0.1 on 2026-01-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['view_order']},
        ),
        migrations.AlterField(
            model_name='task',
            name='view_order',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
