# Generated by Django 6.0.1 on 2026-01-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_task_options_alter_task_view_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
